#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 19 09:29:11 2025

@author: benjamin
"""

# ---- Import Libraries ----
import os
import numpy as np
import Sofa
import SofaRuntime
from stlib3.scene import Scene
from splib3.animation import animate
import Geometries.Constants1 as Const
import rigidification  
import Sofa.Core
import Sofa.constants.Key as Key
from scipy.spatial.transform import Rotation as R 
import h5py 
import matplotlib.pyplot as plt
from BaseFitnessEvaluationController import BaseFitnessEvaluationController

from Generation import MagneticSkin

# ---- Directory Paths ----
dirPath = os.path.dirname(os.path.abspath(__file__)) + '/'
path = os.path.dirname(os.path.abspath(__file__))+'/Meshes/'
MeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'
GeneratedMeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'

TempPath = os.path.dirname(os.path.abspath(__file__))+'/Temp/'
script_dir = os.path.dirname(os.path.abspath(__file__))


EdgeMargin = 0.1 *1e-3 

# --- right BoxROI para el borde derecho ---
BoxROIFixCoords = [
    Const.MagneticSkinLength / 2 + Const.BoxTolerance, 
    Const.MagneticSkinWidth  / 2 + Const.BoxTolerance, 
    Const.MagneticSkinHeight  + Const.BoxTolerance,  
    Const.MagneticSkinLength / 2 - EdgeMargin,       
    -(Const.MagneticSkinWidth / 2 + Const.BoxTolerance),
    - Const.BoxTolerance 
    ]

# --- left BoxROI ---
BoxROIFixCoords1 = [
    -(Const.MagneticSkinLength / 2 - EdgeMargin),           
    Const.MagneticSkinWidth  / 2 + Const.BoxTolerance,   
    Const.MagneticSkinHeight + Const.BoxTolerance,       
    -(Const.MagneticSkinLength / 2 + Const.BoxTolerance),
    -(Const.MagneticSkinWidth / 2 + Const.BoxTolerance), 
    -Const.BoxTolerance     
    ]


level_stretch = "020pct"  # options: "000pct", "010pct", "020pct"   
level_taxels = "10"  # options "10", "40", "160"

stretch_pct = int(level_stretch.replace("pct", ""))/100



def calculate_B_field(distance_r_m, magnetic_moment_direction, mu_magnitude):
    """
    Calculates the magnetic field B generated by a magnetic dipole at a given point.

    Parameters:
    - distance_r_mm: Vector (in mm) from the dipole to the point where the field is measured.
    - magnetic_moment_direction: Unit vector indicating the direction of the magnetic moment.
    - mu_magnitude: Magnitude of the magnetic moment (e.g., in A·m²).

    Returns:
    - B_field_pT: Magnetic field vector at the point, in microTesla (uT).
    """

    # Convert the distance vector to an array and compute its norm
    r = np.array(distance_r_m)  

    r_magnitude = np.linalg.norm(r) 
          
    # print('r_magnitude', r_magnitude)
    # Unit vector in the direction of r
    r_hat = r / r_magnitude
    # print('rhat', r_hat)
    Mu_hat = magnetic_moment_direction
    # Full magnetic moment vector (direction * magnitude)
    mu = [x * mu_magnitude for x in Mu_hat]

    # Compute the dipole field tensor: 3*r̂*r̂ᵀ - I 
    tensor = 3 * np.outer(r_hat, r_hat) - np.identity(3)

    # Apply the formula: B = (μ₀ / 4π) * (tensor ⋅ μ) / |r|³
    numerator = np.matmul(tensor, mu)
    denominator = 4 * np.pi * (abs(r_magnitude)**3)

    # Magnetic field B in Tesla
    B_field = numerator / denominator

    # Convert Tesla to microTesla (1e6) or miliTesla (1e3)
    B_field_pT = B_field * 1e6   # 1000000000000000 
    # print('B_field_pT', B_field_pT)
    return B_field_pT



class FitnessEvaluationController(BaseFitnessEvaluationController):   
    
    def __init__(self, *args, **kwargs):

        print('>>> Start Init SOFA scene ...')

        super(FitnessEvaluationController,self).__init__(*args, **kwargs)

        self.ModelNode = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model     
        # self.RigidMO = kwargs['RigidMO']   
        # self.CableConstraint = self.ModelNode.cables.cable1.CableConstraint
        # self.ReferenceMO = self.rootNode.ReferenceMONode.ReferenceMO
        # self.StartPosition = np.array(self.ReferenceMO.position.value[0])
        # self.StartAngle = math.acos( np.abs(self.StartPosition[2]) / np.linalg.norm(self.StartPosition)) 
        # self.FollowingMO = self.rootNode.model.FollowingMONode.FollowingMO
        
        
        
        # ----- SOFA nodes and objects -----
        # self.RootNode = kwargs['RootNode']
        self.RigidMO = kwargs['RigidMO']
        # self.SensorMO = kwargs['SensorMO']
        self.CFF = kwargs['CFF']
        self.CFFSphereROI = kwargs['CFFSphereROI'] 
        self.CFFMO = kwargs['CFFMO']   
        # self.articulationAngle = kwargs['articulationAngle']

        # Objective evaluation variables
        self.current_iter = 0
        current_objectives = self.config.get_currently_assessed_objectives()
        self.max_iter = max([self.config.get_objective_data()[current_objectives[i]][1] for i in range(len(current_objectives))])






        # ----- Time and PID variables -----
        self.t = 0
        self.dt = 0.01
        self.time = 0
        self.Kp, self.Ki, self.Kd = 100, 1e7, 1e2
        self.integral_vec = np.zeros(3)
        self.prev_error_vec = np.zeros(3)

        self.closest_point = None
        self.closest_index = None
        self.fixed_index = None       # índice del punto más cercano fijado
        self.last_point_index = None  # índice de trayectoria anterior, para detectar cambios
        self.point_index = 0

        self.puntosS = S_trajectory(np.array(self.config.MagnetCenters)[:, :2], height=self.config.Height)
        # print(self.puntosS)
        self.puntotrayectoria = 0
        self.wait_frames = 0
        self.frames_to_wait = 2  # número de frames a esperar antes de fijar el índice

        #Data
        self.data_Force = []
        self.data_MagnetPose = []
        self.data_SensorPose = []
        self.data_MagneticField = []
        self.data_IdenterPosition = []
        self.data_setpoint = []

        self.idx_trayectory = 0
        self.last_force_idx = -1  


        self.wait_counter = 0 
        self.frames_to_wait = 1
        self.just_changed_force = False
        self.waiting = False
        self.quadrant_real = None
        self.forces_real = None


        self.current_point =  0
        self.current_force_idx = 0
        self.force_wait_counter = 0


    def MoveCFFSphereROI(self, pos):   
        self.CFFSphereROI.centers = [pos.tolist()]


    def onAnimateBeginEvent(self, dt):


        # roi_indices = self.CFFSphereROI.indices.value
        # n_roi_indices = len(roi_indices)

        #strecht 
        if self.t == 0:  
            displacement = -3  # in meters
            grab_node = self.rootNode.ExternalRefNode
            grab = grab_node.getObject('ExternalMO')
            if grab is None:
                return
            currentValue = list(grab.translation.value)
            currentValue[0] = displacement
            grab.translation.value = currentValue
            grab.reinit()


            # Cambio aca para que los taxeles se calculen dentro porque tomara los indices del restposition
            tetras = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
            positions = np.array(tetras.position.value)
        base_roi = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('BaseFixROI')
        indices = base_roi.indices.value
        tetras = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
        positions = tetras.position.value


        #   Para que los puntos lleguen a la posicion final 
        if self.t == 30:
            print('holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')


            # rest_positions[indices] = positions[indices]
            # base_positions = [positions[i] for i in indices]
            base_positions = positions[indices]
            # print("Posiciones actuales:", base_positions)
            # tetras.rest_position.value = rest_positions.tolist()

            base_node = self.rootNode.ExternalRefNodeBase
            base = base_node.getObject('ExternalBaseMO')
            print('base.position.value', base.position.value)
            
            base.position.value = base_positions.tolist()
            # print('base.position.value', base.position.value) 
            base.reinit()

            model_spring = self.ModelNode
            spring = model_spring.getObject('BaseFixSpring')
            # n = len(spring.getObject('indices').value)
            # print(f'n={n}')
            print('spring', spring.findData('stiffness').value)
            spring.findData('stiffness').value = [1e12]
            print('spring', spring.findData('stiffness').value)
            indices = spring.findData('points').value
            print("Puntos controlados por el resorte:", indices)
            # spring.reinit()
            #sensor del medio 
            MagnetPose = self.RigidMO.position.value[0:self.config.NMagnets, :]
            # ---- Extract 3D positions of magnets----
            MagnetPosition = MagnetPose[:, :3]
            ext_mo = self.rootNode.ExternalRefNodeBase.getObject('ExternalBaseMO')

            target_positions = ext_mo.position.value

            print("Número de puntos del resorte:", len(indices))
            print("Número de posiciones externas:", len(target_positions))


        # if self.t == 30:

        #     spring = self.ModelNode.getObject('BaseFixSpring')
        #     indices = spring.findData('points').value

        #     tetras = self.ModelNode.getObject('tetras')
        #     positions = tetras.position.value

        #     base_node = self.rootNode.ExternalRefNodeBase
        #     base = base_node.getObject('ExternalBaseMO')

        #     # Tomar la posición ACTUAL del modelo
        #     base_positions = positions[indices]

        #     # Congelar esta forma como referencia
        #     base.position.value = base_positions.tolist()
        #     base.rest_position.value = base_positions.tolist()

        #     base.reinit()

        #     # Activar el resorte
        #     spring.findData('stiffness').value = [1e12]

        #     print("external_rest_shape:",spring.findData('external_rest_shape').value)

                        
            # self.trayectoria_5puntos= np.array(centers_ordened)
            # 0 = center # 1 = nw   # 2 = ne # 3 = se # 4 = sw    



        # force_idx =  [0, 0, 0]
        identer_position = [0, 0, 0]
        idx = -1

        # Fuerza constante
        FORCE_VALUE = -2.5  # Newtons

        if self.t > 30:
            print(f'{self.current_point=}')



            if self.current_point >= len(self.trayectoria_5puntos):
                print("Trajectory ended — saving data")
                # self.save_to_h5()
                return  
            
            # ---------- identer position ----------
            identer_position = self.trayectoria_5puntos[self.current_point]
            self.MoveCFFSphereROI(identer_position)

            # ---------- force ----------
            force_idx = self.CFF.totalForce.value = [0.0, 0.0, FORCE_VALUE]

            # ---------- time ----------
            self.force_wait_counter += 1

            if self.force_wait_counter >= self.frames_to_wait:
                self.force_wait_counter = 0
                self.waiting = True  # Activamos la espera para guardar datos
                self.frames_counter = 0


        # ---- Extract pose of magnets and sensors ----
        MagnetPose = self.RigidMO.position.value[0:self.config.NMagnets, :]
        SensorPose = self.RigidMO.position.value[self.config.NMagnets:, :]


        # ---- Extract 3D positions of magnets and sensors ----
        MagnetPosition = MagnetPose[:, :3]
        SensorPosition = SensorPose[:, :3]

        GlobalMagneticField = []


        for j in range(self.config.NSensors):
            
            LocalMagneticField = []
            quat_sensor = SensorPose[j, 3:7]
            MiR_Sensor = R.from_quat(quat_sensor)

            R_sensor_inv = R.from_quat(quat_sensor).inv()
            rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()

            for i in range(self.config.NMagnets):
                Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
                
                delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global           
                # print(f'Distancia sensor {j} a {i} - imanes:', delta_local)
                quat_Magnet = MagnetPose[i, 3:7]             
                # print(f"i : {i}, quat_iman{quat_Magnet} ")
                MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)               
                rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet
                Direccion_momento_magnetico = rotation_Matrix[:, 2]
                
                # print(f"Direccion momento magnetico iman {i+1} ", Direccion_momento_magnetico)

                LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, self.config.mu_magnitude))

            TotalMagneticField = np.sum(LocalMagneticField, axis=0)
            GlobalMagneticField.append(TotalMagneticField)
            

        GlobalMagneticField = np.array(GlobalMagneticField) #(15, 3)


        self.t += 1
    
    def MoveCFFSphereROI(self, pos):   
        self.CFFSphereROI.centers = [pos.tolist()]
        
    def onAnimateBeginEvent(self, event):
          
        roi_indices = self.CFFSphereROI.indices.value
        n_roi_indices = len(roi_indices)

        #strecht 
        if self.t == 0:  
            displacement = -Const.MagneticSkinWidth * stretch_pct  # in meters
            print(f"Applying stretch displacement: {displacement} m")
            grab_node = self.RootNode.ExternalRefNode
            grab = grab_node.getObject('ExternalMO')
            if grab is None:
                return
            currentValue = list(grab.translation.value)
            currentValue[0] = displacement
            grab.translation.value = currentValue
            grab.reinit()


            # Cambio aca para que los taxeles se calculen dentro porque tomara los indices del restposition
            tetras = self.RootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
            positions = np.array(tetras.position.value)

            xmin, ymin, zmin = positions.min(axis=0)
            xmax, ymax, zmax = positions.max(axis=0)
            
            centers_taxels = get_taxels(xmin= xmin, xmax= xmax, ymin=ymin, ymax=ymax)

            points_trajectory = S_trajectory(centers_taxels)
            centers_ordened = []
            z_target = Const.MagneticSkinHeight
            for center in points_trajectory:
                center_3d = np.array([center[0], center[1], z_target])
                centers_ordened.append(center_3d)
            
            
            self.trayectoria_5puntos= np.array(centers_ordened)




            #load data
            # quadrant_real, forces_real, sample_index= self.loaddata("/home/benjamin/Repos/Mag_Tec_Models/data/Multiple_Points/2.5mm_single_test42/cleaned/raw/data/test_39_020_cleaned.h5")
            # quadrant_real, forces_real, sample_index= self.loaddata("/home/benjamin/Repos/MagTecSkinSofa/Scenes/Results/test_data/sim_experiment_force_0.0to3.0N_step0.1N_single_test50_stretch_000pct.h5")    
            
            # self.quadrant_real = quadrant_real   
            # self.forces_real = forces_real
            # self.index_sequences = np.array(sample_index)
    

        base_roi = self.RootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('BaseFixROI')
        indices = base_roi.indices.value
        tetras = self.RootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
        positions = tetras.position.value
         
        # cff_sphere = self.CFFSphereROI
        # cff_sphere.findData('position').value = tetras.position.value
        # cff_sphere.reinit()

        
        #Para que los puntos lleguen a la posicion final 
        if self.t == 30:
            '''
            positions = np.array(tetras.position.value)

            xmin, ymin, zmin = positions.min(axis=0)
            xmax, ymax, zmax = positions.max(axis=0)
            
            centers_taxels = get_taxels(xmin= xmin, xmax= xmax, ymin=ymin, ymax=ymax)

            points_trajectory = S_trajectory(centers_taxels)
            centers_ordened = []
            z_target = Const.MagneticSkinHeight
            for center in points_trajectory:
                center_3d = np.array([center[0], center[1], z_target])
                centers_ordened.append(center_3d)

            '''

            # points_trajectory_S = np.array(points_trajectory)
            # rest_positions[indices] = positions[indices]
            # base_positions = [positions[i] for i in indices]
            base_positions = positions[indices]
            # print("Posiciones actuales:", base_positions)
            # tetras.rest_position.value = rest_positions.tolist()

            base_node = self.RootNode.ExternalRefNodeBase
            base = base_node.getObject('ExternalBaseMO')
            # print('base.position.value', base.position.value)
            
            base.position.value = base_positions.tolist()
            # print('base.position.value', base.position.value) 
            # base.reinit()

            model_spring = self.RootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model
            spring = model_spring.getObject('BaseFixSpring')
            # print('spring', spring.findData('stiffness').value)
            spring.findData('stiffness').value = [1e12]
            print("external_rest_shape:",spring.findData('external_rest_shape'))

            MagnetPose = self.RigidMO.position.value[0:Const.NMagnets, :]
            # ---- Extract 3D positions of magnets----
            MagnetPosition = MagnetPose[:, :3]

            
            # 0 = center # 1 = nw   # 2 = ne # 3 = se # 4 = sw    



        # force_idx =  [0, 0, 0]
        identer_position = [0, 0, 0]
        idx = -1

        # Force constant
        FORCE_VALUE = -0.5 # Newtons

        if self.t > 30:
            print(f'{self.current_point=}')



            if self.current_point >= len(self.trayectoria_5puntos):
                print("Trayectoria terminada — guardando datos")
                self.save_to_h5()
                os._exit(0)
                return  
            
            # ---------- identer position ----------
            identer_position = self.trayectoria_5puntos[self.current_point]
            self.MoveCFFSphereROI(identer_position)

            # ---------- set force ----------
            force_idx = self.CFF.totalForce.value = [0.0, 0.0, FORCE_VALUE]

            # ---------- time ----------
            self.force_wait_counter += 1

            if self.force_wait_counter >= self.frames_to_wait:
                self.force_wait_counter = 0
                self.waiting = True  # Activamos la espera para guardar datos
                self.frames_counter = 0

        # ---- Extract pose of magnets and sensors ----
        MagnetPose = self.RigidMO.position.value[0:Const.NMagnets, :]
        SensorPose = self.RigidMO.position.value[Const.NMagnets:, :]



        # ---- Extract 3D positions of magnets and sensors ----
        MagnetPosition = MagnetPose[:, :3]
        SensorPosition = SensorPose[:,:3]


        GlobalMagneticField = []


        for j in range(Const.NSensors):
            
            LocalMagneticField = []
            # print(f'Distancia sensor {j} - imanes:', Dist_Sensor)
            quat_sensor = SensorPose[j, 3:7]
            MiR_Sensor = R.from_quat(quat_sensor)

            R_sensor_inv = R.from_quat(quat_sensor).inv()
            rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()
            # rotation_Matrix_Sensor = MiR_Sensor.as_matrix()

            for i in range(Const.NMagnets):
                Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
        #         # pos_iman = Lista_imanes[i]
                
                delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global           
                # print(f'Distancia sensor {j} a {i} - imanes:', delta_local)
                quat_Magnet = MagnetPose[i, 3:7]             
                # print(f"i : {i}, quat_iman{quat_Magnet} ")
                MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)               
                rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet
                Direccion_momento_magnetico = rotation_Matrix[:, 2]
                
                # print(f"Direccion momento magnetico iman {i+1} ", Direccion_momento_magnetico)

                LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, Const.mu_magnitude))

            TotalMagneticField = np.sum(LocalMagneticField, axis=0)
            GlobalMagneticField.append(TotalMagneticField)
            

        GlobalMagneticField = np.array(GlobalMagneticField) #(15, 3)
        # print(f'GlobalMagneticField : {GlobalMagneticField}')



        M_hw =np.array([[12,9,6,3,0],[13,10,7,4,1],[14,11,8,5,2]])
        A_hw = M_hw.flatten()
        sim_to_hw = np.argsort(A_hw) 
        print("sim_to_hw", sim_to_hw)


        GlobalMagneticField_index_real = GlobalMagneticField[sim_to_hw]
        print("GlobalMagneticField index real:", GlobalMagneticField_index_real)

        # GlobalMagneticField_index_real = GlobalMagneticField[A_hw]

        if self.waiting:
                self.frames_counter += 1

                if self.frames_counter >= self.frames_to_wait:
                     
                     
                    if len(self.data_MagneticField) <= self.current_point:
                        self.data_MagneticField.append([])
                        self.data_Force.append([])
                        self.data_IdenterPosition.append([])



                    self.data_MagneticField[self.current_point].append(GlobalMagneticField_index_real)
                    self.data_Force[self.current_point].append(force_idx)
                    self.data_IdenterPosition[self.current_point].append(identer_position)

                    print(f"[Guardado] Force={force_idx}, press={len(self.data_Force[self.current_point])}")
                    print(f"[Guardado] MagneticField_sim={GlobalMagneticField}")
                    print(f"[Guardado] MagneticField_real={GlobalMagneticField_index_real}")    
                    print(f"[Guardado] identer_position={identer_position}")    


                    self.current_point += 1
                    self.waiting = False


        self.t += 1



def createScene(rootNode, config):

              
    # SofaRuntime.importPlugin("ArticulatedSystemPlugin") 
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.ODESolver.Backward')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.AnimationLoop')
    

    pluginsList = [
        'Sofa.Component.Visual',
        'ArticulatedSystemPlugin',
        'SoftRobots',
        "SofaPython3",
        "Sofa.Component.LinearSolver.Iterative",
        "Sofa.Component.ODESolver.Backward",
        'SoftRobots.Inverse',
        'Sofa.Component.AnimationLoop',
        'Sofa.Component.Constraint.Lagrangian.Correction',
        'Sofa.Component.Constraint.Lagrangian.Solver',
        'Sofa.Component.Setting',
        'Sofa.Component.Constraint.Projective',
        'Sofa.Component.IO.Mesh',
        'Sofa.Component.Topology.Container.Dynamic',
        'Sofa.Component.LinearSolver.Direct',
        'Sofa.GL.Component.Shader',
        'Sofa.Component.Mapping.NonLinear',
        'Sofa.Component.Mass',
        'Sofa.Component.SolidMechanics.FEM.Elastic',
        'Sofa.Component.Engine.Select', 
        'Sofa.Component.SolidMechanics.Spring',
        'Sofa.Component.Mapping.Linear', 
        'Sofa.Component.StateContainer',
        'Sofa.Component.Topology.Container.Constant',
        'Sofa.Component.Visual',
        'Sofa.GL.Component.Rendering3D',
        'Sofa.GUI.Component',
        'Sofa.Component.MechanicalLoad'

    ]
    # scene = Scene(rootNode, plugins=pluginsList, iterative=False)
    # scene.addMainHeader()


    for name in pluginsList:
        rootNode.addObject("RequiredPlugin", name=name)

    rootNode.addObject('VisualStyle', displayFlags='hideWireframe showBehaviorModels hideCollisionModels hideBoundingCollisionModels showForceFields showInteractionForceFields')
    rootNode.findData('gravity').value = [0, 0, -9810]
    rootNode.findData('dt').value = 0.02

    rootNode.addObject('FreeMotionAnimationLoop')
    rootNode.addObject('GenericConstraintSolver', tolerance="1e-12", maxIterations="10000")
    # rootNode.addObject('GenericConstraintSolver', maxIterations=1e3, tolerance=1e-5)

    # rootNode.addObject('BackgroundSetting', color='0.1 0.85 0.85')
    # root = Sofa.Core.Node()



    #He tenido que cambiar
    # rootNode.addObject('RequiredPlugin', name='Sofa.GL.Component.Shader')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.Mapping.NonLinear')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.Constraint.Projective')



    rootNode.addObject('DefaultVisualManagerLoop')

    rootNode.addObject('LightManager')
    rootNode.addObject(
        "PositionalLight",
        name="light1",
        color="0.8 0.8 0.8",
        position=[0, 0, 15*1e-3],
    )
    rootNode.addObject(
        "PositionalLight",
        name="light2",
        color="0.8 0.8 0.8",
        position=[0, 0, -15*1e-3],
    )
    

    # rootNode.addObject()
    # ---- Paths to mesh files ----   
    VolumetricMeshPath = GeneratedMeshesPath + 'MagneticSkin.vtk'
    
    SurfaceMeshPath = GeneratedMeshesPath + 'MagneticSkin.stl'

    SurfaceMeshPath_without_rigids = GeneratedMeshesPath + 'MagneticSkin_without_rigids.stl'
    
    
    # rootNode.addObject(SinusoidalController(node=rootNode, RigidMO = RigidMO))
    # rootNode.addObject(FixedController(rootNode))

    #----------------------
    # Goal Node
    #---------------------- 
 
    #----------------------
    # Rigidification - start
    #----------------------          
                   
    completeMesh = rootNode.addChild('completeMesh')
    # completeMesh.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    completeMesh.addObject('MeshVTKLoader', name='loader', 
                    filename = config.get_mesh_filename(mode = "Volume", refine = 0, 
                                                        generating_function = MagneticSkin, 
                                                        length = config.Length, 
                                                        width = config.Width,
                                                        height = config.Height,                                                    
                                                        magnet_boxes=config.MagnetBoxCoords,
                                                        # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                        lc= config.VolumeMeshCharacteristicLength))

    completeMesh.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    completeMesh.init()
    MeshTetra = completeMesh.addObject('MeshTopology', name="AllMesh", src='@loader')

    

    #---- Create BoxROIs ----
    Boxes = []
    for i in range(len(config.rigidObjectsBoxCoords[1:])):
        boxTip = completeMesh.addObject('BoxROI', name='Tip'+str(i), box=[config.rigidObjectsBoxCoords[i+1]], drawBoxes=True, 
                                        tetrahedra="@container.tetrahedra" , position="@container.position")
        Boxes.append(boxTip)
        boxTip.init()

      
    positionAllPoints = MeshTetra.findData('position').value;
    nbPoints = len(positionAllPoints)

    
    IndicesWithRigidIdx = np.empty((0,2), dtype=int)
    
    for (i,Box) in enumerate(Boxes):
        IndicesNP = np.array(Box.indices.value, dtype=int)
        NPoints = len(IndicesNP)
        RigidIdx = np.ones(NPoints,dtype=int)*i
        CurrentIndicesWithRigidIdx = np.append(IndicesNP.reshape((NPoints,1)), RigidIdx.reshape((NPoints,1)),1)
        IndicesWithRigidIdx = np.append(IndicesWithRigidIdx, CurrentIndicesWithRigidIdx,0)
    

    IndicesWithRigidIdxSorted = np.sort(IndicesWithRigidIdx[:,0],0)
    SortedIdxs = np.argsort(IndicesWithRigidIdx[:,0],0)
    SortedRigidIdxs = IndicesWithRigidIdx[:,1][SortedIdxs]
    indicesTip = IndicesWithRigidIdxSorted.tolist()
    rigidBlocks = [IndicesWithRigidIdxSorted.tolist()] 
    
    DeformableIndicesTotal = []    
    
    for i in range(nbPoints):
        if i not in indicesTip:
            DeformableIndicesTotal.append(i)                                 

    freeBlocks = np.sort(DeformableIndicesTotal)    
    IdxsOrderedFreeBlocks = np.argsort(DeformableIndicesTotal)    
    indexPairs = np.array(rigidification.fillIndexPairs(nbPoints,freeBlocks,rigidBlocks))
    NPPointsDeformable = positionAllPoints[DeformableIndicesTotal,:]   
    NPSortedPointsDeformable = NPPointsDeformable[IdxsOrderedFreeBlocks, :]
    PointsDeformable = NPSortedPointsDeformable.flatten().tolist()
    pointsBody = PointsDeformable
    #deformablePoints = pointsBody
       
    pointsTip = np.array(positionAllPoints[indicesTip,:]).flatten().tolist()                                                 
    rigidIndexPerPoint = SortedRigidIdxs.tolist()


    
    solverNode = rootNode.addChild("solverNode")
    solverNode.addObject('EulerImplicitSolver',rayleighStiffness="0.1", rayleighMass="0.1")
    solverNode.addObject('SparseLDLSolver',name='preconditioner')
    solverNode.addObject('GenericConstraintCorrection', linearSolver='@preconditioner')


    RigidNode= solverNode.addChild('RigidNode')
     
    
    nominal_pose = [] 
    TipOrientation = [0, 0, 0, 1]       
    
    
    for center in config.rigidObjects[1:]:
        CurrentPose = center + TipOrientation
        nominal_pose += CurrentPose
    RigidMO = RigidNode.addObject("MechanicalObject",template="Rigid3d",name="RigidMesh", position=nominal_pose, 
                                  showObject=True, showObjectScale=1.4*1e-3, showIndices=True)


    RigidifiedNode =  RigidNode.addChild('RigidifiedNode')   
    RigidifiedNode.addObject('MechanicalObject', name='RigidifiedMesh', position=pointsTip,
                             template='Vec3d', showObject=True, showObjectScale=4*1e-3, showColor=1)       
    RigidifiedNode.addObject("RigidMapping", globalToLocalCoords="true", rigidIndexPerPoint=rigidIndexPerPoint)
    

    # ---- Deformable Node -----
    deformableNode = RigidifiedNode.addChild("deformableNode")
    deformableNode.addObject('PointSetTopologyContainer', position=pointsBody)
    deformableNode.addObject('MechanicalObject', name='DeformableMech', showObject = False, showObjectScale = 4*1e-3)
    # deformableNode.addObject('BarycentricMapping', input='@model/tetras', output='@DeformableMech')
    

    model = deformableNode.addChild('model')
    RigidifiedNode.addChild(model)
    

    	#---- Heart ----
    model.addObject('EulerImplicitSolver', name='nodesolver')          
    model.addObject('ShewchukPCGLinearSolver', iterations='15', name='linearsolver', tolerance='1e-5', update_step='1')
    # model.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)

    model.addObject('MeshVTKLoader', name='loader', 
                filename = config.get_mesh_filename(mode = "Volume", refine = 0, 
                                                    generating_function = MagneticSkin, 
                                                    length = config.Length, 
                                                    width = config.Width,
                                                    height = config.Height,                                                    
                                                    magnet_boxes=config.MagnetBoxCoords,
                                                    # MagnetCenters = config.MagnetCenters,
                                                    # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                    lc= config.VolumeMeshCharacteristicLength))
    model.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    model.addObject('MechanicalObject', name='tetras', template='Vec3', showIndices=False, showIndicesScale='4e-5', rx='0', dz='0')
    model.addObject('UniformMass', totalMass='0.09')
    model.addObject('TetrahedronFEMForceField', template='Vec3', name='FEM', method='large', poissonRatio=Const.PoissonRatio,  youngModulus=Const.YoungsModulus) 
    #CAJA PART1              
    model.addObject('BoxROI', name='BaseROI', box=config.BoxROIFixCoords_base, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    model.addObject('RestShapeSpringsForceField', points='@BaseROI.indices', stiffness='1e12')              
    model.addObject("SubsetMultiMapping",name="subsetMapping",template="Vec3d,Vec3d", input='@'+deformableNode.getPathName()+'/DeformableMech' + ' ' + '@'+RigidifiedNode.getPathName()+'/RigidifiedMesh' , output='@./tetras', indexPairs=indexPairs.tolist())
    #Parte que se mueve para estirar
    model.addObject('BoxROI', name='EndROI', box=config.BoxROIFixCoords1, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    model.addObject('RestShapeSpringsForceField', points='@EndROI.indices', stiffness='1e12', external_rest_shape="@rootNode/ExternalRefNode/ExternalMO")              

    #Parte de la Base Fija
    model.addObject('BoxROI', name='BaseFixROI', box=config.BoxROIFixCoordss, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")            
    model.addObject('RestShapeSpringsForceField', name='BaseFixSpring' , points='@BaseFixROI.indices', stiffness='0', external_rest_shape="@ExternalRefNodeBase/ExternalBaseMO")

    
    # ----------------------------------------
    # Visualization                          
    # ----------------------------------------
    
    modelVisu = model.addChild('visu')
    # modelVisu.addObject('MeshSTLLoader', filename=SurfaceMeshPath, name="loader")
    modelVisu.addObject('MeshSTLLoader', name="loader", 
                    filename = config.get_mesh_filename(mode = "Surface", refine = 0, 
                                                    generating_function = MagneticSkin, 
                                                    length = config.Length, 
                                                    width = config.Width,
                                                    height = config.Height,
                                                    magnet_boxes= config.MagnetBoxCoords,
                                                    lc= config.SurfaceMeshCharacteristicLength))
    modelVisu.addObject('OglModel', src="@loader", scale3d=[1, 1, 1])
    modelVisu.addObject('BarycentricMapping')
    
    #Parte que se mueve
    ExternalRefNode = rootNode.addChild("ExternalRefNode")
    ExternalRefNode.addObject('MechanicalObject', name='ExternalMO', template='Vec3', showObject=True, showObjectScale=15*1e-3, showColor = [0,0,.7],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/EndROI.pointsInROI')

    #Parte para fijar la base 
    ExternalRefNodeBase = rootNode.addChild("ExternalRefNodeBase")
    ExternalRefNodeBase.addObject('MechanicalObject', name='ExternalBaseMO', template='Vec3', showObject=True, showObjectScale=4, showColor = [0,0,.7],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/BaseFixROI.pointsInROI')
    

    #---- Sphere ROI para seleccionar con stl ---- 
    CFFNode = model.addChild('CFFNode')
    CFFNode.addObject('MeshSTLLoader', filename=SurfaceMeshPath_without_rigids, name="loader")
    CFFNode.addObject('MeshSTLLoader', name="loader", 
                    filename = config.get_mesh_filename(mode = "Surface", refine = 0, 
                                                    generating_function = MagneticSkin, 
                                                    length = config.Length, 
                                                    width = config.Width,
                                                    height = config.Height,
                                                    magnet_boxes=config.MagnetBoxCoords,
                                                    # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                    lc= config.SurfaceMeshCharacteristicLength))



    CFFMO = CFFNode.addObject('MechanicalObject', position='@loader.position') 
    # trayectoria_points = S_trajectory(np.array(Const.MagnetCenters)[:, :2])
    CFFSphereROI = CFFNode.addObject('SphereROI', template="Vec3d", name='CFFSphereROI', centers=[0, 0 ,5*1e-3], radii=[Const.indenterRadius], drawSphere=True, drawPoints = True, drawSize=6 )
    CFFSphereROI.init()              
    CFF = CFFNode.addObject('ConstantForceField', name='CFF', template='Vec3', indices='@CFFSphereROI.indices', totalForce=[0, 0, 0], showArrowSize=2*1e-3)                               
    CFFNode.addObject("BarycentricMapping")


    rootNode.addObject(Controller(RootNode=rootNode, RigidMO = RigidMO, CFF=CFF, CFFMO=CFFMO, CFFSphereROI=CFFSphereROI ))

    return rootNode