# -*- coding: utf-8 -*-
"""Config for the SensorFinger"""

__authors__ = "sescaidanavarro, tnavez"
__contact__ = "stefan.escaida@uoh.cl, tanguy.navez@inria.fr"
__version__ = "1.0.0"
__copyright__ = "(c) 2020, Inria"
__date__ = "Oct 28 2022"


import os 
import math
import numpy as np
import Sofa
import h5py 
import time
import rigidification
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation as R 
from BaseFitnessEvaluationController import BaseFitnessEvaluationController

from Generation import MagneticSkin

level_stretch = "000pct"  # options: "000pct", "010pct", "020pct"   
level_taxels = "10"  # options "10", "40", "160"

def calculate_B_field(distance_r_m, magnetic_moment_direction, mu_magnitude):
    """
    Calculates the magnetic field B generated by a magnetic dipole at a given point
    using the standard dipole field equation in SI units.

    Parameters
    ----------
    distance_r_m : array-like, shape (3,)
        Vector (in meters) from the magnetic dipole to the observation point.
    magnetic_moment_direction : array-like, shape (3,)
        Unit vector indicating the direction of the magnetic moment.
    mu_magnitude : float
        Magnitude of the magnetic moment in A·m².

    Returns
    -------
    B_field_uT : ndarray, shape (3,)
        Magnetic field vector at the observation point, in microTesla (µT).
    """

    r = np.array(distance_r_m)  

    r_magnitude = np.linalg.norm(r) 
    r_hat = r / r_magnitude
    Mu_hat = magnetic_moment_direction
    mu = [x * mu_magnitude for x in Mu_hat]

    # Compute the dipole field tensor: 3*r̂*r̂ᵀ - I
    tensor = 3 * np.outer(r_hat, r_hat) - np.identity(3)

    # Apply the formula: B = (μ₀ / 4π) * (tensor ⋅ μ) / |r|³
    numerator = np.matmul(tensor, mu)
    denominator = 4 * np.pi * (abs(r_magnitude)**3)

    # Magnetic field B in Tesla
    B_field = numerator / denominator

    # Convert Tesla to microTesla (1e6) or miliTesla (1e3)
    B_field_uT = B_field * 1e6   

    return B_field_uT
    
def taxel_grid(n):
    k = int(np.log2(np.sqrt(n)))
    p = 2**k

    while n % p != 0:
        p //= 2
    return n // p, p


def get_taxels(
    xmin, xmax,
    ymin, ymax,
    sphere_radius = 3*1e-3,
):
    Nx, Ny = taxel_grid(int(level_taxels))  

    xmin_safe = xmin + sphere_radius
    xmax_safe = xmax - sphere_radius
    ymin_safe = ymin + sphere_radius
    ymax_safe = ymax - sphere_radius
    Lx = xmax_safe - xmin_safe
    Ly = ymax_safe - ymin_safe


    dx = Lx / Nx
    dy = Ly / Ny


    #Taxels centers 
    center_taxels = []
    for iy in range(Ny):
        for ix in range(Nx):

            cx = xmin_safe + (ix + 0.5) * dx
            cy = ymin_safe + (iy + 0.5) * dy

            tid = iy * Nx + ix
            center_taxels.append((cx, cy))

    cx_skin = (xmin + xmax) / 2
    cy_skin = (ymin + ymax) / 2

    return center_taxels



# #llamar a la funcion en onanimateevent con self.config.Height 
# def Normal_Trajectory(point, delta, height):  
#     point1 = np.array([point[0], point[1], height + delta])
#     point2 = np.array([point[0], point[1], height])
#     return point1, point2


def S_trajectory(points, height):
    """
    Generates an S-shaped trajectory
    """

    pts = np.array(points)
    x_vals = np.unique(pts[:, 0])

    trayectoria = []
    invertir = False

    for x in x_vals:
        columna = pts[pts[:, 0] == x]
        columna = columna[np.argsort(columna[:, 1])]
        if invertir:
            columna = columna[::-1]

        for p in columna:
            x_, y_ = p
            trayectoria.append([x_, y_, height])  

        invertir = not invertir

    return np.array(trayectoria)



class FitnessEvaluationController(BaseFitnessEvaluationController):   
    
    def __init__(self, *args, **kwargs):

        print('>>> Start Init SOFA scene ...')

        super(FitnessEvaluationController,self).__init__(*args, **kwargs)

        self.ModelNode = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model     
        # self.RigidMO = kwargs['RigidMO']   
        # self.CableConstraint = self.ModelNode.cables.cable1.CableConstraint
        # self.ReferenceMO = self.rootNode.ReferenceMONode.ReferenceMO
        # self.StartPosition = np.array(self.ReferenceMO.position.value[0])
        # self.StartAngle = math.acos( np.abs(self.StartPosition[2]) / np.linalg.norm(self.StartPosition)) 
        # self.FollowingMO = self.rootNode.model.FollowingMONode.FollowingMO
        
        
        
        # ----- SOFA nodes and objects -----
        # self.RootNode = kwargs['RootNode']
        self.RigidMO = kwargs['RigidMO']
        # self.SensorMO = kwargs['SensorMO']
        self.CFF = kwargs['CFF']
        self.CFFSphereROI = kwargs['CFFSphereROI'] 
        self.CFFMO = kwargs['CFFMO']   
        # self.articulationAngle = kwargs['articulationAngle']

        # Objective evaluation variables
        self.current_iter = 0
        current_objectives = self.config.get_currently_assessed_objectives()
        self.max_iter = max([self.config.get_objective_data()[current_objectives[i]][1] for i in range(len(current_objectives))])






        # ----- Time and PID variables -----
        self.t = 0
        self.dt = 0.01
        self.time = 0
        self.Kp, self.Ki, self.Kd = 100, 1e7, 1e2
        self.integral_vec = np.zeros(3)
        self.prev_error_vec = np.zeros(3)

        self.closest_point = None
        self.closest_index = None
        self.fixed_index = None       # índice del punto más cercano fijado
        self.last_point_index = None  # índice de trayectoria anterior, para detectar cambios
        self.point_index = 0

        self.puntosS = S_trajectory(np.array(self.config.MagnetCenters)[:, :2], height=self.config.Height)
        # print(self.puntosS)
        self.puntotrayectoria = 0
        self.wait_frames = 0
        self.frames_to_wait = 2  # número de frames a esperar antes de fijar el índice

        #Data
        self.data_Force = []
        self.data_MagnetPose = []
        self.data_SensorPose = []
        self.data_MagneticField = []
        self.data_IdenterPosition = []
        self.data_setpoint = []

        self.idx_trayectory = 0
        self.last_force_idx = -1  


        self.wait_counter = 0 
        self.frames_to_wait = 1
        self.just_changed_force = False
        self.waiting = False
        self.quadrant_real = None
        self.forces_real = None


        self.current_point =  0
        self.current_force_idx = 0
        self.force_wait_counter = 0


    def MoveCFFSphereROI(self, pos):   
        self.CFFSphereROI.centers = [pos.tolist()]


    def onAnimateBeginEvent(self, dt):


        # roi_indices = self.CFFSphereROI.indices.value
        # n_roi_indices = len(roi_indices)

        #strecht 
        if self.t == 0:  
            displacement = -3  # in meters
            grab_node = self.rootNode.ExternalRefNode
            grab = grab_node.getObject('ExternalMO')
            if grab is None:
                return
            currentValue = list(grab.translation.value)
            currentValue[0] = displacement
            grab.translation.value = currentValue
            grab.reinit()


            # Cambio aca para que los taxeles se calculen dentro porque tomara los indices del restposition
            tetras = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
            positions = np.array(tetras.position.value)

            xmin, ymin, zmin = positions.min(axis=0)
            xmax, ymax, zmax = positions.max(axis=0)
            
            centers_taxels = get_taxels(xmin= xmin, xmax= xmax, ymin=ymin, ymax=ymax)

            points_trajectory = S_trajectory(centers_taxels, self.config.Height)
            centers_ordened = []
            z_target = self.config.Height
            for center in points_trajectory:
                center_3d = np.array([center[0], center[1], z_target])
                centers_ordened.append(center_3d)
            
            
            self.trayectoria_5puntos = np.array(centers_ordened)
            print(f"trayectoria_5puntos: {self.trayectoria_5puntos}")

        base_roi = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('BaseFixROI')
        indices = base_roi.indices.value
        tetras = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
        positions = tetras.position.value


    #   Para que los puntos lleguen a la posicion final 
        if self.t == 30:
            print('holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')


            # rest_positions[indices] = positions[indices]
            # base_positions = [positions[i] for i in indices]
            base_positions = positions[indices]
            # print("Posiciones actuales:", base_positions)
            # tetras.rest_position.value = rest_positions.tolist()

            base_node = self.rootNode.ExternalRefNodeBase
            base = base_node.getObject('ExternalBaseMO')
            print('base.position.value', base.position.value)
            
            base.position.value = base_positions.tolist()
            # print('base.position.value', base.position.value) 
            base.reinit()

            model_spring = self.ModelNode
            spring = model_spring.getObject('BaseFixSpring')
            # n = len(spring.getObject('indices').value)
            # print(f'n={n}')
            print('spring', spring.findData('stiffness').value)
            spring.findData('stiffness').value = [1e12]
            print('spring', spring.findData('stiffness').value)
            indices = spring.findData('points').value
            print("Puntos controlados por el resorte:", indices)
            # spring.reinit()
            #sensor del medio 
            MagnetPose = self.RigidMO.position.value[0:self.config.NMagnets, :]
            # ---- Extract 3D positions of magnets----
            MagnetPosition = MagnetPose[:, :3]
            ext_mo = self.rootNode.ExternalRefNodeBase.getObject('ExternalBaseMO')

            target_positions = ext_mo.position.value

            print("Número de puntos del resorte:", len(indices))
            print("Número de posiciones externas:", len(target_positions))


        # if self.t == 30:

        #     spring = self.ModelNode.getObject('BaseFixSpring')
        #     indices = spring.findData('points').value

        #     tetras = self.ModelNode.getObject('tetras')
        #     positions = tetras.position.value

        #     base_node = self.rootNode.ExternalRefNodeBase
        #     base = base_node.getObject('ExternalBaseMO')

        #     # Tomar la posición ACTUAL del modelo
        #     base_positions = positions[indices]

        #     # Congelar esta forma como referencia
        #     base.position.value = base_positions.tolist()
        #     base.rest_position.value = base_positions.tolist()

        #     base.reinit()

        #     # Activar el resorte
        #     spring.findData('stiffness').value = [1e12]

        #     print("external_rest_shape:",spring.findData('external_rest_shape').value)

                        
            # self.trayectoria_5puntos= np.array(centers_ordened)
            # 0 = center # 1 = nw   # 2 = ne # 3 = se # 4 = sw    



        # force_idx =  [0, 0, 0]
        identer_position = [0, 0, 0]
        idx = -1

        # Fuerza constante
        FORCE_VALUE = -2.5  # Newtons

        if self.t > 30:
            print(f'{self.current_point=}')



            if self.current_point >= len(self.trayectoria_5puntos):
                print("Trajectory ended — saving data")
                # self.save_to_h5()
                return  
            
            # ---------- identer position ----------
            identer_position = self.trayectoria_5puntos[self.current_point]
            self.MoveCFFSphereROI(identer_position)

            # ---------- force ----------
            force_idx = self.CFF.totalForce.value = [0.0, 0.0, FORCE_VALUE]

            # ---------- time ----------
            self.force_wait_counter += 1

            if self.force_wait_counter >= self.frames_to_wait:
                self.force_wait_counter = 0
                self.waiting = True  # Activamos la espera para guardar datos
                self.frames_counter = 0


        # ---- Extract pose of magnets and sensors ----
        MagnetPose = self.RigidMO.position.value[0:self.config.NMagnets, :]
        SensorPose = self.RigidMO.position.value[self.config.NMagnets:, :]


        # ---- Extract 3D positions of magnets and sensors ----
        MagnetPosition = MagnetPose[:, :3]
        SensorPosition = SensorPose[:, :3]

        GlobalMagneticField = []


        for j in range(self.config.NSensors):
            
            LocalMagneticField = []
            quat_sensor = SensorPose[j, 3:7]
            MiR_Sensor = R.from_quat(quat_sensor)

            R_sensor_inv = R.from_quat(quat_sensor).inv()
            rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()

            for i in range(self.config.NMagnets):
                Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
                
                delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global           
                # print(f'Distancia sensor {j} a {i} - imanes:', delta_local)
                quat_Magnet = MagnetPose[i, 3:7]             
                # print(f"i : {i}, quat_iman{quat_Magnet} ")
                MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)               
                rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet
                Direccion_momento_magnetico = rotation_Matrix[:, 2]
                
                # print(f"Direccion momento magnetico iman {i+1} ", Direccion_momento_magnetico)

                LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, self.config.mu_magnitude))

            TotalMagneticField = np.sum(LocalMagneticField, axis=0)
            GlobalMagneticField.append(TotalMagneticField)
            

        GlobalMagneticField = np.array(GlobalMagneticField) #(15, 3)


        self.t += 1



            # print(f'global magnetic {j}', TotalMagneticField )


        # if self.current_iter == self.max_iter:            
            
        #     current_objectives_names = self.config.get_currently_assessed_objectives()

        #     for i in range(len(current_objectives_names)):

        #         current_objective_name =  current_objectives_names[i]

                # # Sensibility metrics. Reflects the efficiency of a pressure sensor.
                # if "PressureSensibility" == current_objective_name:
                #     CavityVolume = self.ModelNode.Cavity01.SurfacePressureConstraint.cavityVolume.value
                #     Cavity01VolumeGrowth = self.SurfacePressureConstraint1.volumeGrowth.value
                #     Growth = np.abs(Cavity01VolumeGrowth/CavityVolume)
                #     print("Growth differential: ", Growth)
                #     self.objectives.append(Growth)
                    
                # # Sensibility metrics to volume variation. Reflects the efficiency of a volume sensor.
                # if "VolumeSensibility" == current_objective_name:
                #     Cavity01VolumeGrowth = self.SurfacePressureConstraint1.volumeGrowth.value
                #     Growth = np.abs(Cavity01VolumeGrowth)
                #     print("Growth differential: ", Growth)
                #     self.objectives.append(Growth)
                    
                

def createScene(rootNode, config):

              
    # SofaRuntime.importPlugin("ArticulatedSystemPlugin") 
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.ODESolver.Backward')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.AnimationLoop')
    

    pluginsList = [
        'Sofa.Component.Visual',
        'ArticulatedSystemPlugin',
        'SoftRobots',
        "SofaPython3",
        "Sofa.Component.LinearSolver.Iterative",
        "Sofa.Component.ODESolver.Backward",
        'SoftRobots.Inverse',
        'Sofa.Component.AnimationLoop',
        'Sofa.Component.Constraint.Lagrangian.Correction',
        'Sofa.Component.Constraint.Lagrangian.Solver',
        'Sofa.Component.Setting',
        'Sofa.Component.Constraint.Projective',
        'Sofa.Component.IO.Mesh',
        'Sofa.Component.Topology.Container.Dynamic',
        'Sofa.Component.LinearSolver.Direct',
        'Sofa.GL.Component.Shader',
        'Sofa.Component.Mapping.NonLinear',
        'Sofa.Component.Mass',
        'Sofa.Component.SolidMechanics.FEM.Elastic',
        'Sofa.Component.Engine.Select', 
        'Sofa.Component.SolidMechanics.Spring',
        'Sofa.Component.Mapping.Linear', 
        'Sofa.Component.StateContainer',
        'Sofa.Component.Topology.Container.Constant',
        'Sofa.Component.Visual',
        'Sofa.GL.Component.Rendering3D',
        'Sofa.GUI.Component',
        'Sofa.Component.MechanicalLoad'

    ]
    # scene = Scene(rootNode, plugins=pluginsList, iterative=False)
    # scene.addMainHeader()


    for name in pluginsList:
        rootNode.addObject("RequiredPlugin", name=name)

    rootNode.addObject('VisualStyle', displayFlags='hideWireframe showBehaviorModels hideCollisionModels hideBoundingCollisionModels showForceFields showInteractionForceFields')
    rootNode.findData('gravity').value = [0, 0, -9810]
    rootNode.findData('dt').value = 0.02

    rootNode.addObject('FreeMotionAnimationLoop')
    rootNode.addObject('GenericConstraintSolver', tolerance="1e-12", maxIterations="10000")
    # rootNode.addObject('GenericConstraintSolver', maxIterations=1e3, tolerance=1e-5)

    # rootNode.addObject('BackgroundSetting', color='0.1 0.85 0.85')
    # root = Sofa.Core.Node()



    #He tenido que cambiar
    # rootNode.addObject('RequiredPlugin', name='Sofa.GL.Component.Shader')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.Mapping.NonLinear')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.Constraint.Projective')



    rootNode.addObject('DefaultVisualManagerLoop')

    rootNode.addObject('LightManager')
    rootNode.addObject(
        "PositionalLight",
        name="light1",
        color="0.8 0.8 0.8",
        position=[0, 0, 10],
    )
    rootNode.addObject(
        "PositionalLight",
        name="light2",
        color="0.8 0.8 0.8",
        position=[0, 0, -10],
    )
    




    ##################
    ### Load model ###
    ##################



    #----------------------
    # Rigidification - start
    #----------------------          
              

    completeMesh = rootNode.addChild('completeMesh')
    # completeMesh.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)

    completeMesh.addObject('MeshVTKLoader', name='loader', 
                    filename = config.get_mesh_filename(mode = "Volume", refine = 0, 
                                                        generating_function = MagneticSkin, 
                                                        length = config.Length, 
                                                        width = config.Width,
                                                        height = config.Height,                                                    
                                                        magnet_boxes=config.MagnetBoxCoords,
                                                        # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                        lc= config.VolumeMeshCharacteristicLength))

    completeMesh.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    completeMesh.init()


    Boxes = []
    for i in range(len(config.rigidObjectsBoxCoords[1:])):
        boxTip = completeMesh.addObject('BoxROI', name='Tip'+str(i), box=[config.rigidObjectsBoxCoords[i+1]], drawBoxes=True, 
                                        tetrahedra="@container.tetrahedra" , position="@container.position")
        Boxes.append(boxTip)
        boxTip.init()

    

    MeshTetra = completeMesh.addObject('MeshTopology', name="AllMesh", src='@loader')
    positionAllPoints = MeshTetra.findData('position').value;
    nbPoints = len(positionAllPoints)

    IndicesWithRigidIdx = np.empty((0,2), dtype=int)
    
    for (i,Box) in enumerate(Boxes):
        IndicesNP = np.array(Box.indices.value, dtype=int)
        NPoints = len(IndicesNP)
        RigidIdx = np.ones(NPoints,dtype=int)*i
        CurrentIndicesWithRigidIdx = np.append(IndicesNP.reshape((NPoints,1)), RigidIdx.reshape((NPoints,1)),1)
        IndicesWithRigidIdx = np.append(IndicesWithRigidIdx, CurrentIndicesWithRigidIdx,0)
    
    IndicesWithRigidIdxSorted = np.sort(IndicesWithRigidIdx[:,0],0)
    SortedIdxs = np.argsort(IndicesWithRigidIdx[:,0],0)
    SortedRigidIdxs = IndicesWithRigidIdx[:,1][SortedIdxs]

    indicesTip = IndicesWithRigidIdxSorted.tolist()   
    rigidBlocks = [IndicesWithRigidIdxSorted.tolist()] 
    
    DeformableIndicesTotal = []    
    
    for i in range(nbPoints):
        if i not in indicesTip:
            DeformableIndicesTotal.append(i)                                 

    freeBlocks = np.sort(DeformableIndicesTotal)    
    IdxsOrderedFreeBlocks = np.argsort(DeformableIndicesTotal)    
    indexPairs = np.array(rigidification.fillIndexPairs(nbPoints,freeBlocks,rigidBlocks))
    NPPointsDeformable = positionAllPoints[DeformableIndicesTotal,:]   
    NPSortedPointsDeformable = NPPointsDeformable[IdxsOrderedFreeBlocks, :]
    PointsDeformable = NPSortedPointsDeformable.flatten().tolist()
    pointsBody = PointsDeformable
    #deformablePoints = pointsBody
       
    pointsTip = np.array(positionAllPoints[indicesTip,:]).flatten().tolist()                                                 
    rigidIndexPerPoint = SortedRigidIdxs.tolist()

    solverNode = rootNode.addChild("solverNode")
    solverNode.addObject('EulerImplicitSolver',rayleighStiffness="0.1", rayleighMass="0.1")
    solverNode.addObject('SparseLDLSolver',name='preconditioner')
    solverNode.addObject('GenericConstraintCorrection', linearSolver='@preconditioner')


    RigidNode= solverNode.addChild('RigidNode')
     
    
    nominal_pose = [] 
    TipOrientation = [0, 0, 0, 1]       
    
    
    for center in config.rigidObjects[1:]:
        CurrentPose = center + TipOrientation
        nominal_pose += CurrentPose
    RigidMO = RigidNode.addObject("MechanicalObject",template="Rigid3d",name="RigidMesh", position=nominal_pose, 
                                  showObject=True, showObjectScale=1.4*1e-3, showIndices=True)



    RigidifiedNode =  RigidNode.addChild('RigidifiedNode')   
    RigidifiedNode.addObject('MechanicalObject', name='RigidifiedMesh', position=pointsTip,
                             template='Vec3d', showObject=True, showObjectScale=4*1e-3 , showColor=1)       
    RigidifiedNode.addObject("RigidMapping", globalToLocalCoords="true", rigidIndexPerPoint=rigidIndexPerPoint)

    # ---- Deformable Node -----
    deformableNode = RigidifiedNode.addChild("deformableNode")
    deformableNode.addObject('PointSetTopologyContainer', position=pointsBody)
    deformableNode.addObject('MechanicalObject', name='DeformableMech', showObject = False, showObjectScale = 4*1e-3 )
   

    model = deformableNode.addChild('model')
    # model.addChild(rootNode)

    model.addObject('EulerImplicitSolver', name='nodesolver', firstOrder=0, rayleighMass=0.1, rayleighStiffness=0.1)
    model.addObject('SparseLDLSolver', name='precond', template='CompressedRowSparseMatrixd')

    # model.addObject('GenericConstraintCorrection')


    #Simulation solvers
    model.addObject('EulerImplicitSolver', name='nodesolver') 
    model.addObject('ShewchukPCGLinearSolver', iterations='15', name='linearsolver', tolerance='1e-5', update_step='1')
    # model.addObject('GenericConstraintCorrection')


    model.addObject('MeshVTKLoader', name='loader', 
                    filename = config.get_mesh_filename(mode = "Volume", refine = 0, 
                                                        generating_function = MagneticSkin, 
                                                        length = config.Length, 
                                                        width = config.Width,
                                                        height = config.Height,                                                    
                                                        magnet_boxes=config.MagnetBoxCoords,
                                                        # MagnetCenters = config.MagnetCenters,
                                                        # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                        lc= config.VolumeMeshCharacteristicLength))
                            
    model.addObject('TetrahedronSetTopologyContainer', name='container', src='@loader')
    model.addObject('MechanicalObject', name='tetras', template='Vec3d', showIndices='false', showIndicesScale='4e-5')
    model.addObject('UniformMass', totalMass='0.1')
    model.addObject('TetrahedronFEMForceField', template='Vec3d', name='FEM', method='large', poissonRatio=config.PoissonRatio,  youngModulus=config.YoungsModulus)


    #CAJA PART1    
    model.addObject('BoxROI', name='BaseROI', box=config.BoxROIFixCoords_base , drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")  
    model.addObject('RestShapeSpringsForceField', points='@BaseROI.indices', stiffness='1e12')  
    model.addObject("SubsetMultiMapping",name="subsetMapping",template="Vec3d,Vec3d", input='@'+deformableNode.getPathName()+'/DeformableMech' + ' ' + '@'+RigidifiedNode.getPathName()+'/RigidifiedMesh' , output='@./tetras', indexPairs=indexPairs.tolist())
     

    #Parte que se mueve para estirar
    model.addObject('BoxROI', name='EndROI', box=config.BoxROIFixCoords1, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    model.addObject('RestShapeSpringsForceField', name='stretchFixSpring', points='@EndROI.indices', stiffness='0', external_rest_shape="@ExternalRefNode/ExternalMO")              



    #Parte de la Base Fija
    model.addObject('BoxROI', name='BaseFixROI', box=config.BoxROIFixCoords, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")            
    model.addObject('RestShapeSpringsForceField', name='BaseFixSpring' , points='@BaseFixROI.indices', stiffness='0', external_rest_shape="@ExternalRefNodeBase/ExternalBase")


    #Visualization                          
    modelVisu = model.addChild('visu')
    modelVisu.addObject('MeshSTLLoader', name="loader", 
                        filename = config.get_mesh_filename(mode = "Surface", refine = 0, 
                                                        generating_function = MagneticSkin, 
                                                        length = config.Length, 
                                                        width = config.Width,
                                                        height = config.Height,
                                                        magnet_boxes= config.MagnetBoxCoords,
                                                        lc= config.SurfaceMeshCharacteristicLength))
    
    modelVisu.addObject('OglModel', src="@loader", scale3d=[1, 1, 1])
    modelVisu.addObject('BarycentricMapping')


    # 	#---- Sphere ROI ---- 
    CFFNode = model.addChild('CFFNode')
    # CFFNode.addObject('MeshSTLLoader', filename=SurfaceMeshPath, name="loader")
        
    CFFNode.addObject('MeshSTLLoader', name="loader", 
                        filename = config.get_mesh_filename(mode = "Surface", refine = 0, 
                                                        generating_function = MagneticSkin, 
                                                        length = config.Length, 
                                                        width = config.Width,
                                                        height = config.Height,
                                                        magnet_boxes=config.MagnetBoxCoords,
                                                        # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                        lc= config.SurfaceMeshCharacteristicLength))



    CFFMO = CFFNode.addObject('MechanicalObject', position='@loader.position') 
    # trayectoria_points = S_trajectory(np.array(config.MagnetCenters)[:, :2])
    CFFSphereROI = CFFNode.addObject('SphereROI', template="Vec3d", name='CFFSphereROI', centers=[0, 0, 0], radii=[config.indenterRadius], drawSphere=True)
    CFFSphereROI.init() 

    CFF = CFFNode.addObject('ConstantForceField', name='CFF', template='Vec3', indices='@CFFSphereROI.indices', totalForce=[0, 0, -0], showArrowSize = 0.0001*1e-3 )                               
    CFFNode.addObject("BarycentricMapping")


    # #Parte que se mueve
    ExternalRefNode = rootNode.addChild("ExternalRefNode")
    ExternalRefNode.addObject('MechanicalObject', name='ExternalMO', template='Vec3', showObject=True, showObjectScale=15*1e-3, showColor = [0,.7,.0],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/EndROI.pointsInROI')

    #Parte para fijar la base 
    ExternalRefNodeBase = rootNode.addChild("ExternalRefNodeBase")
    ExternalRefNodeBase.addObject('MechanicalObject', name='ExternalBaseMO', template='Vec3', showObject=True, showObjectScale=4 , showColor = [0,0,.7],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/BaseFixROI.pointsInROI')
    
    



    ##################
    ### Controller ###                            
    ##################
    rootNode.addObject(FitnessEvaluationController(name="FitnessEvaluationController", rootNode=rootNode, 
                                                                                        config=config, 
                                                                                        RigidMO = RigidMO, 
                                                                                        CFF = CFF,
                                                                                        CFFMO = CFFMO,
                                                                                        CFFSphereROI = CFFSphereROI
                                                                                        )) 
    
    return rootNode