#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 15 09:29:11 2025

@author: benjamin
"""

# ---- import libraries ----
import numpy as np
import h5py
import os
import itertools
import matplotlib.pyplot as plt
from collections import defaultdict


class Utils:
    @staticmethod
    def minmax_norm(x):
        return (x - x.min()) / (x.max() - x.min() + 1e-8)
    @staticmethod
    def taxel_grid(n):
        k = int(np.log2(np.sqrt(n)))
        p = 2**k

        while n % p != 0:
            p //= 2
        return n // p, p
    
    @staticmethod
    def generate_grid(length, width, margin_x, margin_y, rows, cols):
        '''Generates a 2D grid of (x, y) points within a rectangle'''
        x = np.linspace(-(length - margin_x) / 2, (length - margin_x) / 2, cols)
        y = np.linspace(-(width - margin_y) / 2, (width - margin_y) / 2, rows)
        X, Y = np.meshgrid(x, y)
        return np.column_stack((X.ravel(), Y.ravel()))
    
    @staticmethod
    def generate_infinite_grid(spacing_x, spacing_y, n, angle_deg, origin=(0.0, 0.0)):
        xs = np.arange(-n, n+1) * spacing_x
        ys = np.arange(-n, n+1) * spacing_y
        X, Y = np.meshgrid(xs, ys)
        points = np.column_stack((X.ravel(), Y.ravel()))

        theta = np.deg2rad(angle_deg)
        R = np.array([
            [np.cos(theta), -np.sin(theta)],
            [np.sin(theta),  np.cos(theta)]
        ])
        points = points @ R.T

        points[:, 0] += origin[0]
        points[:, 1] += origin[1]

        return points
    
    @staticmethod
    def cut_grid(points, length, width, margin_x, margin_y):
        xmin = -(length - margin_x) / 2
        xmax = +(length - margin_x) / 2
        ymin = -(width  - margin_y) / 2
        ymax = +(width  - margin_y) / 2

        mask = (
            (points[:, 0] >= xmin) & (points[:, 0] <= xmax) &
            (points[:, 1] >= ymin) & (points[:, 1] <= ymax)
        )
        return points[mask]
    

    @staticmethod
    def get_taxels(xmin, xmax, ymin, ymax, Nx, Ny):
        # for 10 taxels (without margin)
        Lx = xmax - xmin
        Ly = ymax - ymin

        dx = Lx / Nx
        dy = Ly / Ny

        center_taxels = []
        for iy in range(Ny):
            for ix in range(Nx):
                cx = xmin + (ix + 0.5) * dx
                cy = ymin + (iy + 0.5) * dy
                center_taxels.append((cx, cy))

        return center_taxels
    
    
    @staticmethod    
    def getBoxroiCoords(centers, lengths, tolerance):
        '''Generates the coordinates for creating a BoxROI'''
        lx, ly, lz = lengths
        boxes = []

        for px, py, pz in centers:
            box = [
                px - (lx / 2 + tolerance),
                py - (ly / 2 + tolerance),
                pz - (lz / 2 + tolerance),
                px + (lx / 2 + tolerance),
                py + (ly / 2 + tolerance),
                pz + (lz / 2 + tolerance)
            ]
            boxes.append(box)
        return boxes


    @staticmethod
    def S_trajectory(points, heigth):
        """
        Generates an S-shaped trajectory
        """
        pts = np.array(points)
        x_vals = np.unique(pts[:, 0])
        trayectoria = []
        invertir = False

        for x in x_vals:
            columna = pts[pts[:, 0] == x]
            columna = columna[np.argsort(columna[:, 1])]
            if invertir:
                columna = columna[::-1]

            for p in columna:
                x_, y_ = p
                trayectoria.append([x_, y_, heigth])  
            invertir = not invertir

        return np.array(trayectoria)



    @staticmethod
    def calculate_B_field(distance_r_m, magnetic_moment_direction, mu_magnitude):
        """
        Calculates the magnetic field B generated by a magnetic dipole at a given point.

        Parameters:
        - distance_r_mm: Vector (in mm) from the dipole to the point where the field is measured.
        - magnetic_moment_direction: Unit vector indicating the direction of the magnetic moment.
        - mu_magnitude: Magnitude of the magnetic moment (e.g., in A·m²).

        Returns:
        - B_field_pT: Magnetic field vector at the point, in microTesla (uT).
        """

        # Convert the distance vector to an array and compute its norm
        r = np.array(distance_r_m)  
        r_magnitude = np.linalg.norm(r) 
            
        # Unit vector in the direction of r
        r_hat = r / r_magnitude
        Mu_hat = magnetic_moment_direction

        # Full magnetic moment vector (direction * magnitude)
        mu = [x * mu_magnitude for x in Mu_hat]

        # Compute the dipole field tensor: 3*r̂*r̂ᵀ - I 
        tensor = 3 * np.outer(r_hat, r_hat) - np.identity(3)

        # Apply the formula: B = (μ₀ / 4π) * (tensor ⋅ μ) / |r|³
        numerator = np.matmul(tensor, mu)
        denominator = 4 * np.pi * (abs(r_magnitude)**3)

        # Magnetic field B in Tesla
        B_field = numerator / denominator

        # Convert Tesla to microTesla (1e6) or miliTesla (1e3)
        B_field_pT = B_field * 1e6   # 1000000000000000 

        return B_field_pT


    @staticmethod
    def compute_metrics(MagneticField, combinations_k = None):
        """
        Compute mean metric, std metric and per-taxel sums
        for fixed-k sensor combinations.

        Parameters
        ----------
        MagneticField : np.ndarray
            Shape (N_offsets, N_sensors, 3)
        combinations_k : list of tuples
            Sensor index combinations of fixed size k

        Returns
        -------
        metric : np.ndarray
            Mean magnitude per combination
        stds : np.ndarray
            Std magnitude per combination
        order : np.ndarray
            Indices that sort metric (ascending)
        combs : list of tuples
            Sensor combinations
        total_sum_per_taxel : list of np.ndarray
            Each element shape (N_offsets,)
        """

        n_comb = len(combinations_k)
        print('MagneticField.shape', MagneticField.shape)

        metric = np.zeros(n_comb)
        stds = np.zeros(n_comb)
        total_sum_per_taxel = []
        combs = list(combinations_k)

        for i, comb in enumerate(combinations_k):
            sensor_idx = list(comb)

            B_magnitude = np.sqrt(
                MagneticField[:, sensor_idx, 0]**2 +
                MagneticField[:, sensor_idx, 1]**2 +
                MagneticField[:, sensor_idx, 2]**2
            )

            # Sum per taxel (offset)
            B_sum_per_taxel = np.sum(B_magnitude, axis=1)

            metric[i] = np.mean(B_sum_per_taxel)
            stds[i]   = np.std(B_sum_per_taxel)

            total_sum_per_taxel.append(B_sum_per_taxel)

        order = np.argsort(metric)

        return metric, stds, order, combs, total_sum_per_taxel
    
    @staticmethod
    def compute_metric_single_combination(MagneticField, sensor_idx):
        """
        Compute metric and std for a single sensor combination.

        Parameters
        ----------
        MagneticField : np.ndarray
            Shape (N_offsets, N_sensors, 3)
        sensor_idx : list or tuple -> Indices of selected sensors

        Returns
        -------
        metric : float
        
        """

        sensor_idx = list(sensor_idx)

        B_magnitude = np.sqrt(
            MagneticField[:, sensor_idx, 0]**2 +
            MagneticField[:, sensor_idx, 1]**2 +
            MagneticField[:, sensor_idx, 2]**2
        )

        B_sum_per_taxel = np.sum(B_magnitude, axis=1)

        metric = float(np.mean(B_sum_per_taxel))
        std    = float(np.std(B_sum_per_taxel))

        return metric
