#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 19 09:29:11 2025

@author: benjamin
"""

# ---- Import Libraries ----
import os
import numpy as np
import Sofa
import SofaRuntime
from stlib3.scene import Scene
from splib3.animation import animate
import rigidification  
import Sofa.Core
import Sofa.constants.Key as Key
from scipy.spatial.transform import Rotation as R 
import matplotlib.pyplot as plt
from BaseFitnessEvaluationController import BaseFitnessEvaluationController
import itertools
from Generation import MagneticSkin



level_stretch = "000pct"  # options: "000pct", "010pct", "020pct"   
level_taxels = "10"  # options "10", "40", "160"

stretch_pct = int(level_stretch.replace("pct", ""))/100

M_hw =np.array([[12,9,6,3,0],[13,10,7,4,1],[14,11,8,5,2]])
A_hw = M_hw.flatten()
sim_to_hw = np.argsort(A_hw) 


def calculate_B_field(distance_r_m, magnetic_moment_direction, mu_magnitude):
    """
    Calculates the magnetic field B generated by a magnetic dipole at a given point.

    Parameters:
    - distance_r_mm: Vector (in mm) from the dipole to the point where the field is measured.
    - magnetic_moment_direction: Unit vector indicating the direction of the magnetic moment.
    - mu_magnitude: Magnitude of the magnetic moment (e.g., in A·m²).

    Returns:
    - B_field_pT: Magnetic field vector at the point, in microTesla (uT).
    """

    # Convert the distance vector to an array and compute its norm
    r = np.array(distance_r_m)  

    r_magnitude = np.linalg.norm(r) 
          
    # print('r_magnitude', r_magnitude)
    # Unit vector in the direction of r
    r_hat = r / r_magnitude
    # print('rhat', r_hat)
    Mu_hat = magnetic_moment_direction
    # Full magnetic moment vector (direction * magnitude)
    mu = [x * mu_magnitude for x in Mu_hat]

    # Compute the dipole field tensor: 3*r̂*r̂ᵀ - I 
    tensor = 3 * np.outer(r_hat, r_hat) - np.identity(3)

    # Apply the formula: B = (μ₀ / 4π) * (tensor ⋅ μ) / |r|³
    numerator = np.matmul(tensor, mu)
    denominator = 4 * np.pi * (abs(r_magnitude)**3)

    # Magnetic field B in Tesla
    B_field = numerator / denominator

    # Convert Tesla to microTesla (1e6) or miliTesla (1e3)
    B_field_pT = B_field * 1e6   # 1000000000000000 
    # print('B_field_pT', B_field_pT)
    return B_field_pT


def taxel_grid(n):
    k = int(np.log2(np.sqrt(n)))
    p = 2**k

    while n % p != 0:
        p //= 2
    return n // p, p


def get_taxels(xmin, xmax,ymin, ymax,):

    Nx, Ny = taxel_grid(int(level_taxels))  

    Lx = xmax - xmin
    Ly = ymax - ymin

    dx = Lx / Nx
    dy = Ly / Ny

    #Taxels centers 
    center_taxels = []
    for iy in range(Ny):
        for ix in range(Nx):
            cx = xmin + (ix + 0.5) * dx
            cy = ymin + (iy + 0.5) * dy
            center_taxels.append((cx, cy))

    return center_taxels

def S_trajectory(points, heigth):
    """
    Generates an S-shaped trajectory
    """
    pts = np.array(points)
    x_vals = np.unique(pts[:, 0])
    trayectoria = []
    invertir = False

    for x in x_vals:
        columna = pts[pts[:, 0] == x]
        columna = columna[np.argsort(columna[:, 1])]
        if invertir:
            columna = columna[::-1]

        for p in columna:
            x_, y_ = p
            trayectoria.append([x_, y_, heigth])  
        invertir = not invertir

    return np.array(trayectoria)

def compute_metrics(MagneticField, combinations_k):
        """
        Compute mean metric, std metric and per-taxel sums
        for fixed-k sensor combinations.

        Parameters
        ----------
        MagneticField : np.ndarray
            Shape (N_offsets, N_sensors, 3)
        combinations_k : list of tuples
            Sensor index combinations of fixed size k

        Returns
        -------
        metric : np.ndarray
            Mean magnitude per combination
        stds : np.ndarray
            Std magnitude per combination
        order : np.ndarray
            Indices that sort metric (ascending)
        combs : list of tuples
            Sensor combinations
        total_sum_per_taxel : list of np.ndarray
            Each element shape (N_offsets,)
        """

        n_comb = len(combinations_k)

        metric = np.zeros(n_comb)
        stds = np.zeros(n_comb)
        total_sum_per_taxel = []
        combs = list(combinations_k)

        for i, comb in enumerate(combinations_k):
            sensor_idx = list(comb)

            B_magnitude = np.sqrt(
                MagneticField[:, sensor_idx, 0]**2 +
                MagneticField[:, sensor_idx, 1]**2 +
                MagneticField[:, sensor_idx, 2]**2
            )

            # Sum per taxel (offset)
            B_sum_per_taxel = np.sum(B_magnitude, axis=1)

            metric[i] = np.mean(B_sum_per_taxel)
            stds[i]   = np.std(B_sum_per_taxel)

            total_sum_per_taxel.append(B_sum_per_taxel)

        order = np.argsort(metric)

        return metric, stds, order, combs, total_sum_per_taxel
    
def compute_metric(MagneticField):
        """
        Compute mean metric, std metric and per-taxel sums
        for fixed-k sensor combinations.

        Parameters
        ----------
        MagneticField : np.ndarray
            Shape (N_offsets, N_sensors, 3)
        combinations_k : list of tuples
            Sensor index combinations of fixed size k

        Returns
        -------
        metric : np.ndarray
            Mean magnitude per combination
        stds : np.ndarray
            Std magnitude per combination
        order : np.ndarray
            Indices that sort metric (ascending)
        combs : list of tuples
            Sensor combinations
        total_sum_per_taxel : list of np.ndarray
            Each element shape (N_offsets,)
        """


        B_magnitude = np.sqrt(
            MagneticField[:, :, 0]**2 +
            MagneticField[:, :, 1]**2 +
            MagneticField[:, :, 2]**2
        )

        # Sum per taxel (offset)
        B_sum_per_taxel = np.sum(B_magnitude, axis=1)

        metric = np.mean(B_sum_per_taxel)
        std   = np.std(B_sum_per_taxel)

        return metric, std 


class FitnessEvaluationController(BaseFitnessEvaluationController):   
    
    def __init__(self, *args, **kwargs):

        print('>>> Start Init SOFA scene ...')

        super(FitnessEvaluationController,self).__init__(*args, **kwargs)

        self.ModelNode = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model     
  
        # ----- SOFA nodes and objects -----
        # self.RootNode = kwargs['RootNode']
        self.RigidMO = kwargs['RigidMO']
        self.CFF = kwargs['CFF']
        self.CFFSphereROI = kwargs['CFFSphereROI'] 
        self.CFFMO = kwargs['CFFMO']   

        # Objective evaluation variables
        self.current_iter = 0
        current_objectives = self.config.get_currently_assessed_objectives()
        self.max_iter = max([self.config.get_objective_data()[current_objectives[i]][1] for i in range(len(current_objectives))])


        # ----- Time variables -----
        self.t = 0

        self.wait_counter = 0 
        self.frames_to_wait = 10
        self.waiting = False
        self.current_point =  0
        self.current_force_idx = 0
        self.force_wait_counter = 0
        self.offset = None

        # ----- Data -----
        self.data_MagneticField = []

        


        centers_taxels = get_taxels(xmin=-self.config.Length/2,
                                    xmax= self.config.Length/2, 
                                    ymin=-self.config.Width/2, 
                                    ymax= self.config.Width/2)

        points_trajectory = S_trajectory(points=centers_taxels, heigth=self.config.Height)
        centers_ordened = []
        z_target = self.config.Height
        for center in points_trajectory:
            center_3d = np.array([center[0], center[1], z_target])
            centers_ordened.append(center_3d)
        self.trayectoria_5puntos= np.array(centers_ordened)


    def MoveCFFSphereROI(self, pos):   
        self.CFFSphereROI.centers = [pos.tolist()]


    def onAnimateBeginEvent(self, event):

        #strecht 
        if self.t == 0:  
            displacement = -0  # in meters
            grab_node = self.rootNode.ExternalRefNode
            grab = grab_node.getObject('ExternalMO')
            currentValue = list(grab.translation.value)
            currentValue[0] = displacement
            grab.translation.value = currentValue
            grab.reinit()


        if self.t == 30:
            base_roi = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('BaseFixROI')
            indices = base_roi.indices.value
            tetras = self.rootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
            positions = tetras.position.value
            base_positions = positions[indices]

            base_node = self.rootNode.ExternalRefNodeBase
            base = base_node.getObject('ExternalBaseMO')
            
            base.position.value = base_positions.tolist()
            base.reinit()

            model_spring = self.ModelNode
            spring = model_spring.getObject('BaseFixSpring')
            spring.findData('stiffness').value = [1e5]
            indices = spring.findData('points').value

        identer_position = [0, 0, 0]
        set_force = -800000  # ver unidades de medida 

        if self.t > 30:

            if self.current_point >= len(self.trayectoria_5puntos):
                print("Trajectory ended")
                self.t = 0
                self.CFF.totalForce.value = [0.0, 0.0, 0.0]
                self.CFF.reinit()
                self.current_point = 0

            else:
            
                # ---------- identer position ----------
                identer_position = self.trayectoria_5puntos[self.current_point]
                self.MoveCFFSphereROI(identer_position)

                # ---------- set force ----------
                self.CFF.totalForce.value = [0.0, 0.0, set_force]

                # ---------- time ----------
                self.force_wait_counter += 1

                if self.force_wait_counter >= self.frames_to_wait:
                    self.force_wait_counter = 0
                    self.waiting = True  # Activamos la espera para guardar datos
                    self.frames_counter = 0


        # ---- Extract pose of magnets and sensors ----
        SensorPose = self.RigidMO.position.value[0:self.config.NSensors, :]
        MagnetPose = self.RigidMO.position.value[self.config.NSensors:, :]


        # ---- Extract 3D positions of magnets and sensors ----
        MagnetPosition = MagnetPose[:, :3]
        SensorPosition = SensorPose[:, :3]

        GlobalMagneticField = []


        for j in range(self.config.NSensors):
            
            LocalMagneticField = []
            quat_sensor = SensorPose[j, 3:7]
            MiR_Sensor = R.from_quat(quat_sensor)

            R_sensor_inv = MiR_Sensor.inv()
            rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()

            for i in range(self.config.NMagnets):
                Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
                
                delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global           
                quat_Magnet = MagnetPose[i, 3:7]             
                MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)   
                rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet
                Direccion_momento_magnetico = rotation_Matrix[:, 2]
                LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, self.config.mu_magnitude))

            TotalMagneticField = np.sum(LocalMagneticField, axis=0)
            GlobalMagneticField.append(TotalMagneticField)
        
        GlobalMagneticField = np.array(GlobalMagneticField) #(15, 3)

        GlobalMagneticField_index_real = GlobalMagneticField


        # remover el offset, la prueba de los 40 trials la hice sin offset

        # if self.t == 0:
        #     offset = GlobalMagneticField_index_real

        # GlobalMagneticField_index_real = GlobalMagneticField[sim_to_hw] - offset


        if self.offset is None:
            self.offset = GlobalMagneticField_index_real.copy()

        print('Offset', self.offset)

        GlobalMagneticField_index_real = GlobalMagneticField_index_real - self.offset

        print('GlobalMagneticField_index_real', GlobalMagneticField_index_real)
        np.savetxt("campo_global.txt", GlobalMagneticField_index_real)
        

        if self.waiting:
            self.frames_counter += 1

            if self.frames_counter >= self.frames_to_wait:  
              
                if len(self.data_MagneticField) <= self.current_point:
                    self.data_MagneticField.append([])

                self.data_MagneticField[self.current_point].append(GlobalMagneticField_index_real)
                # print('Shape data_MagneticField:', np.array(self.data_MagneticField).shape)
                # print(f"[Guardado] MagneticField_real={GlobalMagneticField_index_real}")    

                self.current_point += 1
                self.waiting = False


        if self.current_iter == self.max_iter-1:
            
            current_objectives_names = self.config.get_currently_assessed_objectives()
            print(f"[Objective] Current objectives: {current_objectives_names}")

            for i in range(len(current_objectives_names)):

                current_objective_name =  current_objectives_names[i]

                if "SensorNumber" == current_objective_name:
                    sensors = self.config.NSensors 
                    print("Number of sensors =", sensors)
                    self.objectives.append(sensors)

                if "MagnetNumber" == current_objective_name:
                    magnets = len(MagnetPose)
                    print("Number of magnets =", magnets)
                    self.objectives.append(magnets)




                if "MagneticSensitivity" == current_objective_name:

                    # metrics_per_stretch = []
                    MagneticField = np.concatenate(self.data_MagneticField, axis=0)
                    metric, std = compute_metric(MagneticField)

                    # metric_000pct, stds_000pct = compute_metric(np.array(self.data_MagneticField_000pct))
                    # print(f"[MagneticSensitivity] MagneticField_000pct metric: {metric_000pct}")
                    # metrics_per_stretch.append(metric_000pct)

                    # metric_010pct, stds_010pct = compute_metric(np.array(self.data_MagneticField_010pct))
                    # print(f"[MagneticSensitivity] MagneticField_010pct metric: {metric_010pct}")
                    # metrics_per_stretch.append(metric_010pct)

                    # metric_020pct, stds_020pct = compute_metric(np.array(self.data_MagneticField_020pct))
                    # print(f"[MagneticSensitivity] MagneticField_020pct metric: {metric_020pct}")
                    # metrics_per_stretch.append(metric_020pct)


                    # metric = np.mean(metrics_per_stretch)
                    # std = np.std(metrics_per_stretch)
                    print(f"[MagneticSensitivity] MagneticField metric: {metric}")
                    print(f"[MagneticSensitivity] MagneticField std: {std}")
                    self.objectives.append(metric)

        self.t += 1
        self.current_iter += 1


    
def createScene(rootNode, config):

              
    # SofaRuntime.importPlugin("ArticulatedSystemPlugin") 
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.ODESolver.Backward')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.AnimationLoop')
    

    pluginsList = [
        'Sofa.Component.Visual',
        'ArticulatedSystemPlugin',
        'SoftRobots',
        "SofaPython3",
        "Sofa.Component.LinearSolver.Iterative",
        "Sofa.Component.ODESolver.Backward",
        'SoftRobots.Inverse',
        'Sofa.Component.AnimationLoop',
        'Sofa.Component.Constraint.Lagrangian.Correction',
        'Sofa.Component.Constraint.Lagrangian.Solver',
        'Sofa.Component.Setting',
        'Sofa.Component.Constraint.Projective',
        'Sofa.Component.IO.Mesh',
        'Sofa.Component.Topology.Container.Dynamic',
        'Sofa.Component.LinearSolver.Direct',
        'Sofa.GL.Component.Shader',
        'Sofa.Component.Mapping.NonLinear',
        'Sofa.Component.Mass',
        'Sofa.Component.SolidMechanics.FEM.Elastic',
        'Sofa.Component.Engine.Select', 
        'Sofa.Component.SolidMechanics.Spring',
        'Sofa.Component.Mapping.Linear', 
        'Sofa.Component.StateContainer',
        'Sofa.Component.Topology.Container.Constant',
        'Sofa.Component.Visual',
        'Sofa.GL.Component.Rendering3D',
        'Sofa.GUI.Component',
        'Sofa.Component.MechanicalLoad'

    ]
    # scene = Scene(rootNode, plugins=pluginsList, iterative=False)
    # scene.addMainHeader()


    for name in pluginsList:
        rootNode.addObject("RequiredPlugin", name=name)

    rootNode.addObject('VisualStyle', displayFlags='hideWireframe showBehaviorModels hideCollisionModels hideBoundingCollisionModels showForceFields showInteractionForceFields')
    rootNode.findData('gravity').value = [0, 0, -9810]
    rootNode.findData('dt').value = 0.02


    rootNode.addObject('FreeMotionAnimationLoop')
    rootNode.addObject('GenericConstraintSolver', tolerance="1e-12", maxIterations="10000")

    # rootNode.addObject('GenericConstraintSolver', maxIterations=1e3, tolerance=1e-5)

    # rootNode.addObject('BackgroundSetting', color='0.1 0.85 0.85')
    # root = Sofa.Core.Node()



    #He tenido que cambiar
    # rootNode.addObject('RequiredPlugin', name='Sofa.GL.Component.Shader')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.Mapping.NonLinear')
    # rootNode.addObject('RequiredPlugin', name='Sofa.Component.Constraint.Projective')


    rootNode.addObject('DefaultVisualManagerLoop')

    rootNode.addObject('LightManager')
    rootNode.addObject("PositionalLight", name="light1", color="0.8 0.8 0.8", position=[0, 0, 25])
    rootNode.addObject("PositionalLight", name="light2", color="0.8 0.8 0.8", position=[0, 0, -7])



    #----------------------
    # Goal Node
    #---------------------- 
 
    #----------------------
    # Rigidification - start
    #----------------------          

    completeMesh = rootNode.addChild('completeMesh')
    # completeMesh.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    completeMesh.addObject('MeshVTKLoader', name='loader', 
                    filename = config.get_mesh_filename(mode = "Volume", refine = 0, 
                                                        generating_function = MagneticSkin, 
                                                        length = config.Length, 
                                                        width = config.Width,
                                                        height = config.Height,                                                    
                                                        magnet_boxes=config.MagnetBoxCoords,
                                                        # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                        lc= config.VolumeMeshCharacteristicLength))

    completeMesh.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    completeMesh.init()
    MeshTetra = completeMesh.addObject('MeshTopology', name="AllMesh", src='@loader')


    #---- Create BoxROIs ----
    Boxes = []
    for i in range(len(config.rigidObjectsBoxCoords[1:])):
        boxTip = completeMesh.addObject('BoxROI', name='Tip'+str(i), box=[config.rigidObjectsBoxCoords[i+1]], drawBoxes=True, 
                                        tetrahedra="@container.tetrahedra" , position="@container.position")
        Boxes.append(boxTip)
        boxTip.init()

      
    positionAllPoints = MeshTetra.findData('position').value;
    nbPoints = len(positionAllPoints)

    
    IndicesWithRigidIdx = np.empty((0,2), dtype=int)
    
    for (i,Box) in enumerate(Boxes):
        IndicesNP = np.array(Box.indices.value, dtype=int)
        NPoints = len(IndicesNP)
        RigidIdx = np.ones(NPoints,dtype=int)*i
        CurrentIndicesWithRigidIdx = np.append(IndicesNP.reshape((NPoints,1)), RigidIdx.reshape((NPoints,1)),1)
        IndicesWithRigidIdx = np.append(IndicesWithRigidIdx, CurrentIndicesWithRigidIdx,0)
    

    IndicesWithRigidIdxSorted = np.sort(IndicesWithRigidIdx[:,0],0)
    SortedIdxs = np.argsort(IndicesWithRigidIdx[:,0],0)
    SortedRigidIdxs = IndicesWithRigidIdx[:,1][SortedIdxs]
    indicesTip = IndicesWithRigidIdxSorted.tolist()
    rigidBlocks = [IndicesWithRigidIdxSorted.tolist()] 
    
    DeformableIndicesTotal = []    
    
    for i in range(nbPoints):
        if i not in indicesTip:
            DeformableIndicesTotal.append(i)                                 

    freeBlocks = np.sort(DeformableIndicesTotal)    
    IdxsOrderedFreeBlocks = np.argsort(DeformableIndicesTotal)    
    indexPairs = np.array(rigidification.fillIndexPairs(nbPoints,freeBlocks,rigidBlocks))
    NPPointsDeformable = positionAllPoints[DeformableIndicesTotal,:]   
    NPSortedPointsDeformable = NPPointsDeformable[IdxsOrderedFreeBlocks, :]
    PointsDeformable = NPSortedPointsDeformable.flatten().tolist()
    pointsBody = PointsDeformable
    #deformablePoints = pointsBody
       
    pointsTip = np.array(positionAllPoints[indicesTip,:]).flatten().tolist()                                                 
    rigidIndexPerPoint = SortedRigidIdxs.tolist()


    
    solverNode = rootNode.addChild("solverNode")
    solverNode.addObject('EulerImplicitSolver',rayleighStiffness="0.1", rayleighMass="0.1")
    solverNode.addObject('SparseLDLSolver',name='preconditioner')
    solverNode.addObject('GenericConstraintCorrection', linearSolver='@preconditioner')


    RigidNode= solverNode.addChild('RigidNode')
     
    
    nominal_pose = [] 
    TipOrientation = [0, 0, 0, 1]       
    
    
    for center in config.rigidObjects[1:]:
        CurrentPose = center + TipOrientation
        nominal_pose += CurrentPose
    RigidMO = RigidNode.addObject("MechanicalObject",template="Rigid3d",name="RigidMesh", position=nominal_pose, 
                                  showObject=True, showObjectScale=1, showIndices=True)


    RigidifiedNode =  RigidNode.addChild('RigidifiedNode')   
    RigidifiedNode.addObject('MechanicalObject', name='RigidifiedMesh', position=pointsTip,
                             template='Vec3d', showObject=True, showObjectScale=3, showColor=1)       
    RigidifiedNode.addObject("RigidMapping", globalToLocalCoords="true", rigidIndexPerPoint=rigidIndexPerPoint)
    

    # ---- Deformable Node -----
    deformableNode = RigidifiedNode.addChild("deformableNode")
    deformableNode.addObject('PointSetTopologyContainer', position=pointsBody)
    deformableNode.addObject('MechanicalObject', name='DeformableMech', showObject = False, showObjectScale = 4)
    # deformableNode.addObject('BarycentricMapping', input='@model/tetras', output='@DeformableMech')
    

    model = deformableNode.addChild('model')
    RigidifiedNode.addChild(model)
    

    	#---- Heart ----
    # model.addObject('EulerImplicitSolver', name='nodesolver')          
    # model.addObject('ShewchukPCGLinearSolver', iterations='15', name='linearsolver', tolerance='1e-5', update_step='1')


    model.addObject('MeshVTKLoader', name='loader', 
                filename = config.get_mesh_filename(mode = "Volume", refine = 0, 
                                                    generating_function = MagneticSkin, 
                                                    length = config.Length, 
                                                    width = config.Width,
                                                    height = config.Height,                                                    
                                                    magnet_boxes=config.MagnetBoxCoords,
                                                    # MagnetCenters = config.MagnetCenters,
                                                    # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                    lc= config.VolumeMeshCharacteristicLength))
    
    model.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    model.addObject('MechanicalObject', name='tetras', template='Vec3', showIndices=False, showIndicesScale='4e-5', rx='0', dz='0')
    model.addObject('UniformMass', totalMass='0.09')
    model.addObject('TetrahedronFEMForceField', template='Vec3', name='FEM', method='large', poissonRatio=config.PoissonRatio,  youngModulus=config.YoungsModulus) 
    #CAJA PART1              
    model.addObject('BoxROI', name='BaseROI', box=config.BoxROIFixCoords_base, drawBoxes=False, position="@tetras.rest_position", tetrahedra="@container.tetrahedra", drawPoints = False, drawSize = 3)              
    model.addObject('RestShapeSpringsForceField', points='@BaseROI.indices', stiffness='1e10')

              
    model.addObject("SubsetMultiMapping",name="subsetMapping",template="Vec3d,Vec3d", input='@'+deformableNode.getPathName()+'/DeformableMech' + ' ' + '@'+RigidifiedNode.getPathName()+'/RigidifiedMesh' , output='@./tetras', indexPairs=indexPairs.tolist())

        #Parte que se mueve para estirar
    model.addObject('BoxROI', name='EndROI', box=config.BoxROIFixCoords1, drawBoxes=False, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    # model.addObject('RestShapeSpringsForceField', points='@EndROI.indices', stiffness='1e12', external_rest_shape="@/ExternalRefNode/ExternalMO")              

    #Parte de la Base Fija (se mueven los nodos y se fijan en t=30)
    model.addObject('BoxROI', name='BaseFixROI', box=config.BoxROIFixCoords, drawBoxes=False, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")            
    # model.addObject('RestShapeSpringsForceField', name='BaseFixSpring' , points='@BaseFixROI.indices', stiffness='0', external_rest_shape="@/ExternalRefNodeBase/ExternalBaseMO")


    #    #Parte que se mueve
    ExternalRefNode = rootNode.addChild("ExternalRefNode")
    ExternalRefNode.addObject('MechanicalObject', name='ExternalMO', template='Vec3', showObject=True, showObjectScale=3, showColor = [0,.7,.0],
                                showIndices=False, showIndicesScale=4e-5,
                                position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/EndROI.pointsInROI')

    #Parte para fijar la base 
    ExternalRefNodeBase = rootNode.addChild("ExternalRefNodeBase")
    ExternalRefNodeBase.addObject('MechanicalObject', name='ExternalBaseMO', template='Vec3', showObject=True, showObjectScale=3, showColor = [0,0,.7],
                                    showIndices=False, showIndicesScale=4e-5,
                                    position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/BaseFixROI.pointsInROI')
                        

    model.addObject('RestShapeSpringsForceField',name='StretchFixSpring', points='@EndROI.indices', stiffness='1e8', external_rest_shape='@ExternalRefNode/ExternalMO')

    model.addObject('RestShapeSpringsForceField',name='BaseFixSpring', points='@BaseFixROI.indices', stiffness='0', external_rest_shape='@ExternalRefNodeBase/ExternalBaseMO')

        
    # ----------------------------------------
    # Visualization                          
    # ----------------------------------------
    modelVisu = model.addChild('visu')
    modelVisu.addObject('MeshSTLLoader', name="loader", 
                    filename = config.get_mesh_filename(mode = "Surface", refine = 0, 
                                                    generating_function = MagneticSkin, 
                                                    length = config.Length, 
                                                    width = config.Width,
                                                    height = config.Height,
                                                    magnet_boxes= config.MagnetBoxCoords,
                                                    lc= config.SurfaceMeshCharacteristicLength))
    

    modelVisu.addObject('OglModel', src="@loader", scale3d=[1, 1, 1])
    modelVisu.addObject('BarycentricMapping')
    

    #---- Sphere ROI para seleccionar con stl ---- 
    CFFNode = model.addChild('CFFNode')
    # CFFNode.addObject('MeshSTLLoader', filename=SurfaceMeshPath_without_rigids, name="loader")
    CFFNode.addObject('MeshSTLLoader', name="loader", 
                    filename = config.get_mesh_filename(mode = "Surface", refine = 0, 
                                                    generating_function = MagneticSkin, 
                                                    length = config.Length, 
                                                    width = config.Width,
                                                    height = config.Height,
                                                    magnet_boxes=None,
                                                    # lc_surface = config.SurfaceMeshCharacteristicLength,
                                                    lc= config.SurfaceMeshCharacteristicLength))

    CFFMO = CFFNode.addObject('MechanicalObject', position='@loader.position') 
    CFFSphereROI = CFFNode.addObject('SphereROI', template="Vec3d", name='CFFSphereROI', centers=[0, 0 ,5*1e-3], radii=[config.indenterRadius], drawSphere=False, drawPoints = False, drawSize=6 )
    CFFSphereROI.init()              
    CFF = CFFNode.addObject('ConstantForceField', name='CFF', template='Vec3', indices='@CFFSphereROI.indices', totalForce=[0, 0, 0], showArrowSize=0.1*1e-3)                               
    CFFNode.addObject("BarycentricMapping")


    # return rootNode
    rootNode.addObject(FitnessEvaluationController(name="FitnessEvaluationController", rootNode=rootNode, 
                                                                                        config=config, 
                                                                                        RigidMO = RigidMO, 
                                                                                        CFF = CFF,
                                                                                        CFFMO = CFFMO,
                                                                                        CFFSphereROI = CFFSphereROI
                                                                                        )) 
    
    return rootNode